spring.application.name=billing

server.port=8080



logging.level.org.springframework.security=INFO
server.error.include-message=always
server.error.include-binding-errors=always

spring.data.mongodb.uri=$Add Your MongoDB Url

jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000

