spring.application.name=billing

server.port=8080



logging.level.org.springframework.security=INFO
server.error.include-message=always
server.error.include-binding-errors=always
# It will use the cloud environment variable MONGO_URI if it exists, otherwise it will use your local string
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://kishore:1203@cluster0.hsj5upm.mongodb.net/billing?retryWrites=true&w=majority&appName=Cluster0}

jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000

